# Site settings
title: Crafty Charms
url: https://bansd.github.io
baseurl: 

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"

plugins:
  - jekyll-feed
  - jekyll-paginate